### ISSUE TITLE
Organization Name Change

### ISSUE THREAD

**Issue by alabgh01** [jacobluber/PathologySearchComparison#2]
RhazesLab organization account has changed to KimiaLabMayo. I noticed that your link to Yottixel still points to https://github.com/RhazesLab/yottixel/tree/main which may break.

**Comment by SadeghNasr** [comment]
Thank you! Fixed in https://github.com/jacobluber/PathologySearchComparison/commit/361a27da0f0e2eb6544363a1eb3005d473087fa1
